#title: Thi Bao Ngoc Duong
#logo: /assets/profile_img.png
#description: text below image
#theme: jekyll-theme-minimal

theme: jekyll-theme-minimal
title: Thi Bao Ngoc Duong
logo: /assets/profile_img.png
description: Master's Student in IT | Business Analytics | Data Science
show_downloads: false
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache
include: ["assets/style.css"]
